# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('project_key', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('project_sonar_url', models.CharField(max_length=500)),
            ],
        ),
    ]
