# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='project_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='components',
            name='project_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='components',
            name='project_sonar_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
