# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_auto_20170111_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_on_date', models.CharField(blank=True, max_length=200)),
                ('automatic', models.IntegerField()),
                ('manual', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='components',
            name='project_key',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='components',
            name='project_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='testcases',
            name='comp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.Components'),
        ),
    ]
