# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quality_metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_on_date', models.DateTimeField()),
                ('sabre_defects_open', models.IntegerField()),
                ('customer_defects_open', models.IntegerField()),
                ('internal_defects_backlog', models.IntegerField()),
                ('customer_defects_backlog', models.IntegerField()),
                ('automatic_test_cases', models.IntegerField()),
                ('manual_manual_test_cases', models.IntegerField()),
                ('functional_coverage', models.CharField(max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_metrics.Project')),
            ],
        ),
    ]
