# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_metrics', '0002_auto_20170131_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quality_metric',
            old_name='manual_manual_test_cases',
            new_name='manual_test_cases',
        ),
    ]
