# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_metrics', '0003_auto_20170201_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality_metric',
            name='functional_coverage',
            field=models.IntegerField(),
        ),
    ]
